# syntax=docker/dockerfile:1

ARG NODE_VERSION
ARG DISTRO_NAME=bullseye

FROM node:$NODE_VERSION-$DISTRO_NAME-slim

ARG DISTRO_NAME


# Dependencies
# Using --mount to speed up build with caching, see https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md#run---mount
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  --mount=type=tmpfs,target=/var/log \
  rm -f /etc/apt/apt.conf.d/docker-clean; \
  echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache; \
  apt-get update -qq && \
  DEBIAN_FRONTEND=noninteractive apt-get -yq dist-upgrade && \
  DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
  build-essential \
  gnupg2 \
  curl \
  less \
  git \
  vim

# Create a directory for the app code
RUN mkdir -p /app
WORKDIR /app

EXPOSE 5173

CMD ["/bin/bash"]
